### ISSUE TITLE
entity.name.function.js scope not applied to arrow functions inside class definitions

### ISSUE THREAD

**Issue by kylebebak** [Thom1729/Sublime-JS-Custom#43]
### Env
Running Sublime Text build 3176 on OSX, version v1.0.22 of this package.

### Steps to repro
Paste this code into the editor.

```js
import React from 'react'


const Test = ({ a, b }) => {
  f1 = (e) => {
    e.preventDefault()
  }

  return null
}

export default Test


class TestComponent extends React.Component {
  f2 = (e) => {
    e.preventDefault()
  }

  render() {
    return null
  }
}
```

Set the syntax to **JS Custom - React** or **JS Custom - Default** and hit <kbd>cmd+R</kbd>. The function identifier **f2** isn't indexed, because the `entity.name.function.js` scope isn't applied to it.

If you set the syntax on the view to **JavaScript** and hit <kbd>cmd+R</kbd>, **f2** is indexed, which is correct, but so are other symbols which are neither function nor class definitions.

Also, if you save the file and hit <kbd>shift+cmd+R</kbd> to see all indexed symbols in the project, **f2** is indexed correctly.

### Other observations
It seems that the base JavaScript syntax applies the correct scope to arrow functions defined inside class definitions, while the JS Custom syntaxes do not.

@Thom1729 
I'm really happy you're working on this plugin. `babel-sublime` dev has been inactive for most of the last two years, so I'm hoping this plugin is the way forward for writing JS in Sublime Text. If there's anything you'd like help with, let me know.

Finally, great decision to piggyback as much as possible on the new JavaScript syntax. Reading about why you decided to do that is what made me switch to this package from Babel Sublime.

**Comment by Thom1729** [comment]
I'm seeing the same behavior between the core JavaScript syntax and JS Custom. `f2` is not indexed because the class property code doesn't check for function assignments. This should be addressed in core; I'll see if I can write a PR in the next couple of days.

You're seeing that the core syntax is indexing `f2`?

**Comment by kylebebak** [comment]
>You're seeing that the core syntax is indexing f2?

It's a good thing you asked! I had extracted the core `JavaScript` package into the Packages directory at some point to look at it. I removed it, **and now the core JavaScript syntax and JS Custom are indexing the same symbols**.

Here's a screenshot to show exactly which symbols are indexed.

<img width="1280" alt="screen shot 2018-09-05 at 10 27 30 am" src="https://user-images.githubusercontent.com/1524088/45104118-f0036d80-b0f6-11e8-9ce3-41ae3574fdad.png">


I'm pretty confident that now I'm running the same code as you are. But I noticed another issue that's a bit bizarre, which is seen in the following screenshot. When I hit `shift+cmd+R` to look at all indexed symbols in the project, and not just the ones in the current file, fewer symbols are indexed than when I hit `cmd+R`.

In particular, `f1`, which is correctly indexed in the screenshot above, is no longer indexed in the screenshot below. This happens with both the core JS syntax and JS Custom.

<img width="1280" alt="screen shot 2018-09-05 at 10 29 25 am" src="https://user-images.githubusercontent.com/1524088/45104219-2f31be80-b0f7-11e8-90e5-f9705f0d35cc.png">

**Comment by Thom1729** [comment]
I wonder if **Goto symbol in project** is using a different syntax for some reason. Or maybe the old symbols are cached -- have you restarted Sublime since removing the old JavaScript package?

**Comment by kylebebak** [comment]
Yeah, I've restarted it, and I've also tried creating a new module with the same code, just with the class and method names changed. **Goto symbol in project** still fails to index methods declared inside a functional component or class.

**Update**: this is _really_ bizarre. This screenshot shows a functional component with one of its inner methods (`f1a`) indexed, but the methods `b1` and `c1` are not indexed. Restarting Sublime Text doesn't cause `b1` and `c1` to be indexed. Running **Indexing Status** from the command palette says that it's "idle".

<img width="1280" alt="screen shot 2018-09-05 at 1 27 26 pm" src="https://user-images.githubusercontent.com/1524088/45113352-c276ee00-b10f-11e8-8818-2a471a8d3c52.png">

However, if I run **Goto symbol**, symbols `b1` and `c1` are correctly indexed.

<img width="1280" alt="screen shot 2018-09-05 at 1 35 08 pm" src="https://user-images.githubusercontent.com/1524088/45113659-9019c080-b110-11e8-9385-12320a5b35e4.png">


I think we can definitely say the issue isn't due to caching. What about when you try this? Do you see discrepancies between **Goto symbol** and **Goto symbol in project**?

I would split this into different issues, but I'm not sure how many bugs are really here.

**Comment by kylebebak** [comment]
Ok, I just tried changing the name of `b1` above to `b1a`, and now it's indexed properly by **Goto symbol in project**.

<img width="1280" alt="screen shot 2018-09-05 at 1 38 13 pm" src="https://user-images.githubusercontent.com/1524088/45113809-f868a200-b110-11e8-8093-701d1629ca58.png">

It appears as though that symbol matching in **Goto symbol in project** ignores methods that end in a number, while **Goto symbol** does not.

I'm no concerned about **Goto symbol in project** not indexing methods that end in a number. What is very concerning is that the symbol matching for this command is definitely not the same as the symbol matching for **Goto symbol**.

I have no idea why this is the case, but it's not what I've experienced with other languages.

**Comment by igormigas** [comment]
This issue bothers me as well. Hope you will have a chance to add this arrow function names in classes.

**Comment by Thom1729** [comment]
Fixed upstream and released in v1.0.23.

**Comment by kylebebak** [comment]
Rad!!!

Thanks a bunch!

**Comment by kylebebak** [comment]
@Thom1729 

Hmmm... I installed ST build 3182, which includes the upstream fixes you mentioned, and am running JS Custom v1.0.23.

```js
class A {
  method = () => {}
}
```

If I set the syntax to plain **JavaScript**, `method` is indexed, which means the upstream fix works.

However, if I set the syntax to **JS Custom - Default** or **JS Custom - React**, `method` is not indexed.

I tried removing the **User/JS Custom** folder and rebuilding the syntaxes to no avail. I also tried uninstalling JS Custom and reinstalling it.

I am using the default `JS Custom.sublime-settings` that ship with the plugin. Any ideas?
